title: Kiran's ServiceNow Academy
description: Daily ServiceNow Study Course
theme: just-the-docs

url: "https://Kirans-Gits.github.io"

aux_links:
  GitHub Repository: https://github.com/Kirans-Gits/mastering-servicenow

color_scheme: dark

search_enabled: true

heading_anchors: true
